services:
  database:
    image: postgres:16
    volumes:
      - directus_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER:-directus}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-directus}
      POSTGRES_DB: ${DB_DATABASE:-directus}
    healthcheck:
      test: [CMD-SHELL, 'pg_isready -U ${DB_USER:-directus} -d ${DB_DATABASE:-directus}']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  cache:
    image: redis:7-alpine
    healthcheck:
      test: [CMD, redis-cli, ping]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  directus:
    image: directus/directus:11.14.0
    ports:
      - 8055:8055
    volumes:
      - directus_uploads:/directus/uploads
      - ./extensions:/directus/extensions
    depends_on:
      database:
        condition: service_healthy
      cache:
        condition: service_healthy
    environment:
      SECRET: ${DIRECTUS_SECRET:-change-me-to-a-random-string}

      ADMIN_EMAIL: ${ADMIN_EMAIL:-admin@example.com}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD:-d1r3ctu5}

      DB_CLIENT: pg
      DB_HOST: database
      DB_PORT: 5432
      DB_DATABASE: ${DB_DATABASE:-directus}
      DB_USER: ${DB_USER:-directus}
      DB_PASSWORD: ${DB_PASSWORD:-directus}

      CACHE_ENABLED: true
      CACHE_AUTO_PURGE: true
      CACHE_STORE: redis
      REDIS: redis://cache:6379

      EXTENSIONS_AUTO_RELOAD: true
      WEBSOCKETS_ENABLED: true

volumes:
  directus_data: {}
  directus_uploads: {}
